In [18]:
import sklearn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.datasets import load_boston

In [19]:
boston_dataset = load_boston()
for k,v in boston_dataset.items():
    print(k.upper())
    print('-'*80)
    print(type(v))
    print(v)
    print('')
    print('')

DATA
--------------------------------------------------------------------------------
<class 'numpy.ndarray'>
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


TARGET
--------------------------------------------------------------------------------
<class 'numpy.ndarray'>
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23

In [20]:
## LOAD DADASET
boston_data = boston_dataset['data']                  # NDARRAY
boston_feature_names = boston_dataset['feature_names']


boston_df = pd.DataFrame(data=boston_data, columns=boston_feature_names)
boston_df['price']= boston_dataset['target']


In [21]:
print(boston_df)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(boston_df[boston_dataset['feature_names']], boston_df['price'], random_state=0, test_size=0.33)

In [22]:
## LINEAR REGRESSION
from sklearn.linear_model import LinearRegression


lr = LinearRegression().fit(train_x, train_y)
print(lr.score(train_x, train_y))
print(lr.score(test_x, test_y))   # LR SCORE : R2 SCORE 

0.7677157140026538
0.6705795412578777


In [ ]:
# R2 SCORE 에 대한 해석 KR : https://blog.naver.com/lingua/221525365004

??lr.score

In [24]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
import inspect


for eachRegressor in [LinearRegression,
                      DecisionTreeRegressor, 
                      RandomForestRegressor,
                      GradientBoostingRegressor]:
    
    # TRAINING (FIT)
    er = eachRegressor().fit(train_x, train_y)
    # print(inspect.getsource(eachRegressor().fit))
    # VALIDATION (SCORE)
    print(er)
    print("TRAIN DATASET SCORE:", er.score(train_x, train_y))
    print("TEST  DATASET SCORE:", er.score(test_x, test_y))
    print("TEST  DATASET PREDICTION", er.predict(test_x[:5]))
    
    
    # ONE LINE PARSING LIST
    print("TEST  DATASET PREDICTION", [round(float(prd),2) for prd in  er.predict(test_x[:5])])
    print('-'*100)

LinearRegression()
TRAIN DATASET SCORE: 0.7677157140026538
TEST  DATASET SCORE: 0.6705795412578777
TEST  DATASET PREDICTION [25.05724449 24.05407999 29.25938099 12.05750131 21.18581162]
TEST  DATASET PREDICTION [25.06, 24.05, 29.26, 12.06, 21.19]
----------------------------------------------------------------------------------------------------
DecisionTreeRegressor()
TRAIN DATASET SCORE: 1.0
TEST  DATASET SCORE: 0.6797264596033317
TEST  DATASET PREDICTION [23.1 24.7 20.6 19.1 20.8]
TEST  DATASET PREDICTION [23.1, 24.7, 20.6, 19.1, 20.8]
----------------------------------------------------------------------------------------------------
RandomForestRegressor()
TRAIN DATASET SCORE: 0.9824684372347832
TEST  DATASET SCORE: 0.8184264063244546
TEST  DATASET PREDICTION [23.875 27.278 22.167 10.569 20.333]
TEST  DATASET PREDICTION [23.87, 27.28, 22.17, 10.57, 20.33]
----------------------------------------------------------------------------------------------------
GradientBoostingRegressor(

In [ ]:
## https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html
## https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
## https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html



In [25]:
params = {'n_estimators': 500,
          'max_depth': 4,
          'learning_rate': 0.01}

gbr = GradientBoostingRegressor(**params)
gbr = GradientBoostingRegressor(n_estimators=500, max_depth=4, learning_rate=0.01)

gbr.fit(train_x, train_y)
print("TRAIN DATASET SCORE:", gbr.score(train_x, train_y))
print("TEST  DATASET SCORE:", gbr.score(test_x, test_y))

TRAIN DATASET SCORE: 0.9876008022081595
TEST  DATASET SCORE: 0.8386180004096432


In [26]:
## HYPER PARAMETER TUNING FROM SCRATCH

params = {'n_estimators': 400,
          'max_depth': 3,
          'learning_rate': 0.04,}

for ne in [100,200,400,800]:
    for md in [3,5,7,9]:
        for lr in [0.04, 0.01, 0.02]:
            gbr = GradientBoostingRegressor(n_estimators=ne, max_depth=md, learning_rate=lr)
            gbr.fit(train_x, train_y)
            print(f"TRAIN / TEST / {md} / {ne} / {lr} / %.3f / %.3f" %(gbr.score(train_x, train_y), gbr.score(test_x, test_y)))
            

TRAIN / TEST / 3 / 100 / 0.04 / 0.964 / 0.819
TRAIN / TEST / 3 / 100 / 0.01 / 0.772 / 0.677
TRAIN / TEST / 3 / 100 / 0.02 / 0.915 / 0.792
TRAIN / TEST / 5 / 100 / 0.04 / 0.993 / 0.814
TRAIN / TEST / 5 / 100 / 0.01 / 0.830 / 0.672
TRAIN / TEST / 5 / 100 / 0.02 / 0.960 / 0.793
TRAIN / TEST / 7 / 100 / 0.04 / 0.999 / 0.829
TRAIN / TEST / 7 / 100 / 0.01 / 0.853 / 0.664
TRAIN / TEST / 7 / 100 / 0.02 / 0.976 / 0.798
TRAIN / TEST / 9 / 100 / 0.04 / 1.000 / 0.812
TRAIN / TEST / 9 / 100 / 0.01 / 0.863 / 0.658
TRAIN / TEST / 9 / 100 / 0.02 / 0.981 / 0.775
TRAIN / TEST / 3 / 200 / 0.04 / 0.981 / 0.834
TRAIN / TEST / 3 / 200 / 0.01 / 0.914 / 0.788
TRAIN / TEST / 3 / 200 / 0.02 / 0.964 / 0.818
TRAIN / TEST / 5 / 200 / 0.04 / 0.998 / 0.814
TRAIN / TEST / 5 / 200 / 0.01 / 0.960 / 0.793
TRAIN / TEST / 5 / 200 / 0.02 / 0.993 / 0.813
TRAIN / TEST / 7 / 200 / 0.04 / 1.000 / 0.832
TRAIN / TEST / 7 / 200 / 0.01 / 0.976 / 0.798
TRAIN / TEST / 7 / 200 / 0.02 / 0.999 / 0.828
TRAIN / TEST / 9 / 200 / 0.04 / 1.

In [29]:
## XGBoost VS sklearn Comparison
from sklearn.metrics import mean_squared_error
import xgboost as xgb

params = {'n_estimators': 400,
          'max_depth': 3,
          'learning_rate': 0.04}


gbr = GradientBoostingRegressor(**params)

gbr.fit(train_x, train_y)
gbr_pred_y= gbr.predict(test_x)


xgbr = xgb.XGBRegressor(**params)
xgbr.fit(train_x, train_y,
         eval_set=[(test_x, test_y)],
         eval_metric = 'rmse',
         verbose = False)

xgb_pred_y = xgbr.predict(test_x)




In [28]:
print(gbr_pred_y[:10])
print(xgb_pred_y[:10])

[23.71619237 31.83116123 22.47646892 10.5871928  21.56501985 20.30638435
 21.45057867 20.74162747 22.1219301  18.11060913]
[24.282211 27.157354 22.799631 10.612749 21.373272 20.26328  21.288889
 20.698767 24.749306 17.425259]


In [30]:
gbr_rmse = mean_squared_error(test_y, gbr_pred_y, squared=False)
xgb_rmse = mean_squared_error(test_y, xgb_pred_y, squared=False)

print(gbr_rmse, xgb_rmse)

3.537334366130767 3.9273594461693535


In [ ]:
## 이론 5분
## https://www.slideshare.net/freepsw/boosting-bagging-vs-boosting
